// @ts-nocheck

const database = {
  fr: {
    "skills": "Compétences",
    "contact": "Contact",
    "languages": "Langues",
    "summary": "Résumé",
    "work-exp": "Expérience professionnelle",
    "education": "Éducation",
    "hobbies": "Loisirs",
    "dev-full-stack": "Développeur JS Full-Stack",
    "dev-front-end": "Développeur Front-End",
    "junior-web-dev": "Développeur Web Junior",
    "dev-system": "Développeur Système",
    "10-yrs-exp": "10 ans d'expérience",
    "sports-list": "Sports : escalade, trail, VTT, randonnée, snowboard, apnée, kayak",
    "new-technologies": "Nouvelles technologies",
    "music": "Musique",
    "games": "Jeux vidéos et de société",
    "ecology": "Écologie",
    "gastronomy": "Gastronomie et cuisine",
    "travels": "Voyage",
    "oec": "CDI",
    "int": "STAGE",
    "to-date": "à",
    "iut": "IUT",
    "dut": "DUT Informatique",
    "french": "Français",
    "english": "Anglais",
    "spoken": "Parlé",
    "read-written": "Lu et écrit"
  },
  en: {
    "skills": "Skills",
    "contact": "Contact",
    "languages": "Languages",
    "summary": "Summary",
    "work-exp": "Work Experience",
    "education": "Education",
    "hobbies": "HoWbbies",
    "dev-full-stack": "Full-Stack JS Developer",
    "dev-front-end": "Front-End Developer",
    "junior-web-dev": "Junior Web Developer",
    "dev-system": "System Developer",
    "10-yrs-exp": "10 years of experience",
    "sports-list": "Sports : climbing, trail, mountain bike, hiking, snowboard, apnea, kayak",
    "new-technologies": "New technologies",
    "music": "Music",
    "games": "Videos & Board games",
    "ecology": "Ecology",
    "gastronomy": "Gastronomy & cooking",
    "travels": "Travels",
    "oec": "CDI",
    "int": "INT",
    "to-date": "to",
    "iut": "University Institute of Technology",
    "dut": "University diploma in computer technology",
    "french": "French",
    "english": "English",
    "spoken": "Spoken",
    "read-written": "Read/Written"
  }
}

export const translate = (key = '', lang = 'en') => database[key] || ''